"""Tests for the generation pipeline (Phase 6).

Covers:
  - Dry-run mode (context + prompt built, no API call)
  - Full generation with mocked provider
  - Error handling at each pipeline stage
  - Provider receives correct context and prompt
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any
from unittest.mock import MagicMock, patch

import pytest

from conftest import commit_all, init_repo, write_file


def _make_args(**kwargs) -> argparse.Namespace:
    """Build a minimal argparse.Namespace for cmd_generate."""
    defaults = {
        "path": None,
        "provider": None,
        "model": None,
        "output": None,
        "config": None,
        "dry_run": False,
        "commit": False,
        "command": None,
    }
    defaults.update(kwargs)
    return argparse.Namespace(**defaults)


class MockProvider:
    """A mock provider that records calls and returns canned responses."""

    generate_calls: list[tuple[Any, str]] = []

    def __init__(self, config: dict | None = None):
        self.config = config or {}

    def name(self) -> str:
        return "mock"

    def generate(self, context: Any, prompt: str) -> str:
        MockProvider.generate_calls.append((context, prompt))
        return "# Mock Handoff Document\n\nGenerated by mock provider."

    def validate_config(self, config: dict) -> bool:
        return True

    def is_configured(self) -> bool:
        return True


class FailingProvider:
    """A provider that always fails on generate()."""

    def __init__(self, config: dict | None = None):
        self.config = config or {}

    def name(self) -> str:
        return "failing"

    def generate(self, context: Any, prompt: str) -> str:
        raise RuntimeError("Provider deliberately failed")

    def validate_config(self, config: dict) -> bool:
        return True

    def is_configured(self) -> bool:
        return True


@pytest.fixture(autouse=True)
def _clear_mock_calls():
    """Reset MockProvider.generate_calls before each test."""
    MockProvider.generate_calls.clear()
    yield
    MockProvider.generate_calls.clear()


# ===================================================================
# Dry-run mode
# ===================================================================

class TestDryRun:
    def test_dry_run_shows_context_summary(self, tmp_path: Path) -> None:
        from handoff_agent.cli import cmd_generate

        repo = tmp_path / "repo"
        init_repo(repo)
        write_file(repo, "main.py", "print('hello')")
        commit_all(repo, "initial")

        args = _make_args(dry_run=True, path=str(repo))
        rc = cmd_generate(args)
        assert rc == 0

    def test_dry_run_shows_prompt(self, tmp_path: Path) -> None:
        from handoff_agent.cli import cmd_generate

        repo = tmp_path / "repo"
        init_repo(repo)
        write_file(repo, "README.md", "# Test Project")
        commit_all(repo, "initial")

        args = _make_args(dry_run=True, path=str(repo))
        rc = cmd_generate(args)
        assert rc == 0

    def test_dry_run_no_api_call(self, tmp_path: Path) -> None:
        from handoff_agent.cli import cmd_generate

        repo = tmp_path / "repo"
        init_repo(repo)
        write_file(repo, "app.py", "x = 1")
        commit_all(repo, "initial")

        args = _make_args(dry_run=True, path=str(repo))
        rc = cmd_generate(args)
        assert rc == 0

    def test_dry_run_with_explicit_provider(self, tmp_path: Path) -> None:
        from handoff_agent.cli import cmd_generate

        repo = tmp_path / "repo"
        init_repo(repo)
        write_file(repo, "data.json", "{}")
        commit_all(repo, "initial")

        args = _make_args(dry_run=True, provider="claude", path=str(repo))
        rc = cmd_generate(args)
        assert rc == 0

    def test_dry_run_fails_on_non_git_dir(self, tmp_path: Path) -> None:
        from handoff_agent.cli import cmd_generate

        plain = tmp_path / "plain"
        plain.mkdir()

        args = _make_args(dry_run=True, path=str(plain))
        rc = cmd_generate(args)
        assert rc == 1


# ===================================================================
# Full generation with mocked provider
# ===================================================================

class TestFullGeneration:
    def test_generate_calls_provider(self, tmp_path: Path) -> None:
        from handoff_agent.cli import cmd_generate

        repo = tmp_path / "repo"
        init_repo(repo)
        write_file(repo, "app.py", "print('hello')")
        commit_all(repo, "initial")

        with patch(
            "handoff_agent.providers.factory._PROVIDERS",
            {"mock": MockProvider},
        ):
            args = _make_args(provider="mock", path=str(repo))
            rc = cmd_generate(args)

        assert rc == 0

    def test_generate_receives_full_context(self, tmp_path: Path) -> None:
        from handoff_agent.cli import cmd_generate
        from handoff_agent.context_builder import FullContext

        repo = tmp_path / "repo"
        init_repo(repo)
        write_file(repo, "main.py", "x = 1")
        write_file(repo, "README.md", "# Test")
        commit_all(repo, "initial")

        with patch(
            "handoff_agent.providers.factory._PROVIDERS",
            {"mock": MockProvider},
        ):
            args = _make_args(provider="mock", path=str(repo))
            rc = cmd_generate(args)

        assert rc == 0
        assert len(MockProvider.generate_calls) == 1
        context, prompt = MockProvider.generate_calls[0]
        assert isinstance(context, FullContext)
        assert context.project.name == "repo"

    def test_generate_receives_prompt_with_files(self, tmp_path: Path) -> None:
        from handoff_agent.cli import cmd_generate

        repo = tmp_path / "repo"
        init_repo(repo)
        write_file(repo, "main.py", "x = 1")
        write_file(repo, "README.md", "# Test")
        commit_all(repo, "initial")

        with patch(
            "handoff_agent.providers.factory._PROVIDERS",
            {"mock": MockProvider},
        ):
            args = _make_args(provider="mock", path=str(repo))
            rc = cmd_generate(args)

        assert rc == 0
        context, prompt = MockProvider.generate_calls[0]
        assert "main.py" in prompt
        assert "README.md" in prompt

    def test_generate_prints_provider_output(self, tmp_path: Path) -> None:
        from handoff_agent.cli import cmd_generate

        repo = tmp_path / "repo"
        init_repo(repo)
        write_file(repo, "app.py", "pass")
        commit_all(repo, "initial")

        with patch(
            "handoff_agent.providers.factory._PROVIDERS",
            {"mock": MockProvider},
        ):
            args = _make_args(provider="mock", path=str(repo))
            rc = cmd_generate(args)

        assert rc == 0

    def test_generate_returns_zero_on_success(self, tmp_path: Path) -> None:
        from handoff_agent.cli import cmd_generate

        repo = tmp_path / "repo"
        init_repo(repo)
        write_file(repo, "main.py", "pass")
        commit_all(repo, "initial")

        with patch(
            "handoff_agent.providers.factory._PROVIDERS",
            {"mock": MockProvider},
        ):
            args = _make_args(provider="mock", path=str(repo))
            rc = cmd_generate(args)

        assert rc == 0


# ===================================================================
# Error handling
# ===================================================================

class TestGenerateErrors:
    def test_non_git_directory_returns_error(self, tmp_path: Path) -> None:
        from handoff_agent.cli import cmd_generate

        plain = tmp_path / "plain"
        plain.mkdir()

        args = _make_args(provider="claude", path=str(plain))
        rc = cmd_generate(args)
        assert rc == 1

    def test_provider_failure_returns_error(self, tmp_path: Path) -> None:
        from handoff_agent.cli import cmd_generate

        repo = tmp_path / "repo"
        init_repo(repo)
        write_file(repo, "app.py", "pass")
        commit_all(repo, "initial")

        with patch(
            "handoff_agent.providers.factory._PROVIDERS",
            {"failing": FailingProvider},
        ):
            args = _make_args(provider="failing", path=str(repo))
            rc = cmd_generate(args)

        assert rc == 1

    def test_missing_api_key_returns_error(self, tmp_path: Path) -> None:
        from handoff_agent.cli import cmd_generate

        repo = tmp_path / "repo"
        init_repo(repo)
        write_file(repo, "app.py", "pass")
        commit_all(repo, "initial")

        args = _make_args(provider="claude", path=str(repo))
        rc = cmd_generate(args)
        assert rc == 1


# ===================================================================
# Security boundary verification
# ===================================================================

class TestSecurityBoundary:
    def test_provider_receives_full_context(self, tmp_path: Path) -> None:
        """Verify provider.generate() is called with (FullContext, str)."""
        from handoff_agent.cli import cmd_generate
        from handoff_agent.context_builder import FullContext

        repo = tmp_path / "repo"
        init_repo(repo)
        write_file(repo, "main.py", "x = 1")
        commit_all(repo, "initial")

        with patch(
            "handoff_agent.providers.factory._PROVIDERS",
            {"mock": MockProvider},
        ):
            args = _make_args(provider="mock", path=str(repo))
            rc = cmd_generate(args)

        assert rc == 0
        assert len(MockProvider.generate_calls) == 1
        context, prompt = MockProvider.generate_calls[0]

        assert isinstance(context, FullContext)
        assert isinstance(prompt, str)
        assert hasattr(context, "project")
        assert hasattr(context, "git")
        assert hasattr(context, "files")
        assert hasattr(context, "security")

    def test_provider_cannot_access_secrets(self, tmp_path: Path) -> None:
        """Secret files should be excluded from context by SecurityFilter."""
        from handoff_agent.cli import cmd_generate

        repo = tmp_path / "repo"
        init_repo(repo)
        write_file(repo, ".env", "password=abc123")
        write_file(repo, "app.py", "pass")
        commit_all(repo, "initial")

        with patch(
            "handoff_agent.providers.factory._PROVIDERS",
            {"mock": MockProvider},
        ):
            args = _make_args(provider="mock", path=str(repo))
            rc = cmd_generate(args)

        assert rc == 0
        context, prompt = MockProvider.generate_calls[0]
        file_paths = [f.path for f in context.files]
        assert not any("env" in p.lower() for p in file_paths)

    def test_context_has_project_metadata(self, tmp_path: Path) -> None:
        """Context must contain project name, type, and root."""
        from handoff_agent.cli import cmd_generate

        repo = tmp_path / "myproject"
        init_repo(repo)
        write_file(repo, "pyproject.toml", "[project]\nname = 'test'")
        commit_all(repo, "initial")

        with patch(
            "handoff_agent.providers.factory._PROVIDERS",
            {"mock": MockProvider},
        ):
            args = _make_args(provider="mock", path=str(repo))
            rc = cmd_generate(args)

        assert rc == 0
        context, _ = MockProvider.generate_calls[0]
        assert context.project.name == "myproject"
        assert context.project.project_type == "Python"
        assert str(repo) in context.project.root

    def test_context_has_git_info(self, tmp_path: Path) -> None:
        """Context must contain branch, head, clean status."""
        from handoff_agent.cli import cmd_generate

        repo = tmp_path / "repo"
        init_repo(repo)
        write_file(repo, "app.py", "pass")
        commit_all(repo, "initial")

        with patch(
            "handoff_agent.providers.factory._PROVIDERS",
            {"mock": MockProvider},
        ):
            args = _make_args(provider="mock", path=str(repo))
            rc = cmd_generate(args)

        assert rc == 0
        context, _ = MockProvider.generate_calls[0]
        assert context.git.branch == "main"
        assert context.git.head is not None
        assert context.git.clean is True
